# Simple test configuration for Rustrland v0.3.1
[rustrland]
plugins = ["expose", "scratchpads"]

[rustrland.variables]
term_classed = "foot --app-id"

# Basic scratchpad
[scratchpads.term]
command = "[term_classed] dropterm"
class = "dropterm"
size = "75% 60%"
position = "center"
animation = "fromTop"

# Enhanced expose plugin (v0.3.1)
[expose]
scale = 0.3
padding = 25
background_color = "#000000CC"
highlight_color = "#FF6600"
animation = "fromTop"
animation_duration = 250
max_windows = 30
enable_caching = true
mouse_selection = true