# Configuration de test pour vérifier le fix fromRight
[rustrland]
plugins = ["scratchpads"]

[scratchpads.test_terminal]
animation = "fromTop"
command = "foot"
class = "foot"
size = "75% 60%"
position = "12.5% 20%"

[scratchpads.test_filemanager]
animation = "fromRight"
command = "thunar"
class = "thunar"
size = "50% 80%"
position = "25% 10%"