name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: Crates

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Build binaire en release
      - name: Build
        run: cargo build --release

      # Publication sur crates.io (DÉSACTIVÉE)
      - name: Skip crates.io publication
        run: echo "Publication sur crates.io désactivée"

      # Installation de cargo-deb
      - name: Install cargo-deb
        run: cargo install cargo-deb

      # Génération du .deb
      - name: Build Debian package
        run: cargo deb

      # Installation de git-cliff pour générer le changelog
      - name: Install git-cliff
        run: cargo install git-cliff

      # Génération du changelog depuis les commits
      - name: Generate changelog
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          git cliff --tag "$TAG_NAME" --output CHANGELOG.md

      # Upload du binaire, du .deb et du changelog dans la Release GitHub
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          files: |
            target/release/rustrland
            target/release/rustr
            target/debian/*.deb
