name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Build binaire en release
      - name: Build
        run: cargo build --release

      # Publication sur crates.io
      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}

      # Installation de cargo-deb
      - name: Install cargo-deb
        run: cargo install cargo-deb

      # Génération du .deb
      - name: Build Debian package
        run: cargo deb

      # Installation de git-cliff pour générer le changelog
      - name: Install git-cliff
        run: cargo install git-cliff

      # Génération du changelog depuis les commits
      - name: Generate changelog
        run: git cliff --tag ${{ github.ref_name }} --output CHANGELOG.md

      # Upload du binaire, du .deb et du changelog dans la Release GitHub
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          files: |
            target/release/*           # binaires
            target/debian/*.deb        # paquet Debian
